In [1]:
import torch
from torch import nn

In [2]:
torch.cuda.device_count()

1

In [14]:
device = 'cuda:0'
x = torch.tensor([1.0, 2, 3], device=device)
x.device

device(type='cuda', index=0)

In [15]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=device)
net(x)

tensor([0.3086], device='cuda:0', grad_fn=<ViewBackward0>)

In [16]:
net[0].weight.data.device

device(type='cuda', index=0)

In [24]:
def corr2d(X, K):
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i + h, j:j + w] * K).sum()
    return Y

In [25]:
X = torch.arange(12.0).reshape(3, 4)
K = torch.ones((2, 2))
corr2d(X, K)

tensor([[10., 14., 18.],
        [26., 30., 34.]])

In [30]:
class Conv2D(nn.Module):
    def __init__(self, kernel_size):
        super().__init__()
        self.weight = nn.Parameter(torch.rand(kernel_size))
        self.bias = nn.Parameter(torch.zeros(1))

    def forward(self, X):
        return corr2d(X, self.weight) + self.bias
        

In [31]:
X = torch.ones((6, 8))
X[:, 2:6] = 0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [33]:
K = torch.tensor([[1.0, -1.0]])
Y = corr2d(X, K)
Y

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])